In [1]:
# 1. 기존 꼬인 라이브러리 강제 삭제 및 캐시 제거
!pip uninstall -y jpype1 konlpy
!apt-get purge -y openjdk-8-jdk-headless

# 2. 자바 및 라이브러리 새로 설치 (캐시 사용 안 함)
!apt-get install -y openjdk-8-jdk-headless > /dev/null
!pip install --no-cache-dir --upgrade "jpype1>=1.5.0" konlpy

WARNING: Skipping jpype1 as it is not installed.
WARNING: Skipping konlpy as it is not installed.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'openjdk-8-jdk-headless' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
Collecting jpype1>=1.5.0
  Downloading jpype1-1.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from jpype1>=1.5.0) (25.0)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from konlpy) (6.0.2)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.12/dist-packages (from konlpy) (2.0.2)
Downloading jpype1-1.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (495 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 495.9/495.9 kB 31.3 MB/s eta 0:00:00
Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 274.6 MB/s eta 0:00:00
Installing collected packages: jpype1, konlpy
Successfully installed jpype1-1.6.0 konlpy-0.6.0

In [2]:
import os
# 재시작 후 끊어진 자바 경로를 다시 연결 (가장 중요)
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"

from konlpy.tag import Okt
try:
    okt = Okt()
    print("성공했습니다:", okt.morphs("이제 제발 좀 되라"))
except Exception as e:
    print("에러 내용:", e)

에러 내용: Can't find org.jpype.jar support library

In [2]:
from konlpy.tag import Twitter
from konlpy.tag import Okt
from konlpy.tag import Kkma

In [3]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

train_df = pd.read_csv('ratings_train.txt', sep='\t')
train_df.head(3)

         id                           document  label
0   9976970                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                  너무재밓었다그래서보는것을추천한다      0

In [4]:
print(train_df.info())
train_df['label'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB
None

label
0    75173
1    74827
Name: count, dtype: int64

In [5]:
import re

train_df = train_df.fillna(' ')
# 정규 표현식을 이용하여 숫자를 공백으로 변경(정규 표현식으로 \d 는 숫자를 의미함.)
train_df['document'] = train_df['document'].apply(lambda x: re.sub(r"\d+", " ", x))

# 테스트 데이터 셋을 로딩하고 동일하게 Null 및 숫자를 공백으로 변환.
test_df = pd.read_csv('ratings_test.txt', sep='\t')
test_df = train_df.fillna(' ')
test_df['document'] = test_df['document'].apply(lambda x: re.sub(r"\d+", " ", x))

# id 컬럼 삭제 수행.
train_df.drop('id', axis=1, inplace=True)
test_df.drop('id', axis=1, inplace=True)

In [6]:
from konlpy.tag import Okt

okt = Okt()
def tw_tokenizer(text):
    # 입력 인자로 들어온 text 를 형태소 단어로 토큰화 하여 list 객체 반환
    tokens_ko = okt.morphs(text)
    return tokens_ko

#tw_tokenizer('아버지가방에 들어가신다')
okt.morphs('아버지가방에 들어가신다')

RuntimeError: Can't find org.jpype.jar support library

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Okt 객체의 morphs( ) 객체를 이용한 tokenizer를 사용. ngram_range는 (1,2)
tfidf_vect = TfidfVectorizer(tokenizer=tw_tokenizer, ngram_range=(1,2), min_df=3, max_df=0.9)
tfidf_vect.fit(train_df['document'])
tfidf_matrix_train = tfidf_vect.transform(train_df['document'])

In [ ]:
# Logistic Regression 을 이용하여 감성 분석 Classification 수행.
lg_clf = LogisticRegression(random_state=0, solber='liblinear')

# Parameter C 최적화를 위해 GridSearchCV 를 이용.
params = { 'C': [1 ,3.5, 4.5, 5.5, 10 ] }
grid_cv = GridSearchCV(lg_clf, param_grid=params, cv=3, scoring='accuracy', verbose=1)
grid_cv.fit(tfidf_matrix_train, train_df['label'])
print(grid_cv.best_params_, round(grid_cv.best_score_, 4))

In [ ]:
from sklearn.metrics import accuracy_score

# 학습 데이터를 적용한 TfidfVectorizer를 이용하여 테스트 데이터를 TF-IDF 값으로 Feature 변환함.
tfidf_matrix_test = tfidf_vect.transform(test_df['document'])

# classifier 는 GridSearchCV에서 최적 파라미터로 학습된 classifier를 그대로 이용
best_estimator = grid_cv.best_estimator_
preds = best_estimator.predict(tfidf_matrix_test)

print('Logistic Regression 정확도: ', accuracy_score(test_df['label'], preds))